<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Student Details Form')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="stu_name"><span><?= $block->
                                escapeHtmlAttr(__('Student Name')) ?></span></label>
                            <div class="control">
                                <input name="stu_name" id="stu_name" title="stu_name" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="stu_email"><span><?= $block->
                                escapeHtmlAttr(__('Student Email')) ?></span></label>
                            <div class="control">
                                <input name="stu_email" id="stu_email" title="stu_email" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="message"><span><?= $block->escapeHtmlAttr(__('Message')) ?></span></label>
                            <div class="control">
                                <textarea name="message" id="message" title="message" value="" class="input-text"
                                       type="text" data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Save Record')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>